CREATE ROLE openstreetmap PASSWORD 'openstreetmap' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE DATABASE openstreetmap OWNER openstreetmap ENCODING 'UTF8';
CREATE DATABASE osm_test OWNER openstreetmap ENCODING 'UTF8';
CREATE DATABASE osm OWNER openstreetmap ENCODING 'UTF8';

